<<<<<<< HEAD
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  image: stable
  apt_packages:
    - libusb-1.0.0-dev

python:
  version: 3.7
  install:
    - requirements: software/requirements.txt
    - method: setuptools
      path: .

submodules:
  include:
    - tutorials
  recursive: true
=======
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  image: stable
  apt_packages:
    - libusb-1.0.0-dev

python:
  version: 3.7
  install:
    - requirements: software/requirements.txt
    - method: setuptools
      path: .
>>>>>>> 472949068b6a25514b25f18da3e71c39b06c8fcc
